### PR TITLE
[rmkit] Fix a couple double_click edge cases

### PR DESCRIPTION
**Pull request by mrichards42**
I realized there are a couple edge cases to deal w/ for double_click:

* two quick touches very far apart (= two single_click events)
* move after the second down event (= single_click plus drag_start)

### CODE REVIEW

**Review by raisjn — APPROVED** [review]
what should happen with double click and second click has drag? (for me, it acts as single click + ignores drag?)

**Comment by mrichards42** [comment]
> what should happen with double click and second click has drag? (for me, it acts as single click + ignores drag?)

that's the intent. if I do a quick down + up + down and then drag I get single_click plus drag.

**Comment by raisjn** [comment]
makes sense

**Comment by mrichards42** [comment]
I haven't been able to reproduce single_click + no drag, but I'll keep looking. In the mean time I'm pretty sure just single_click is an improvement from what it was before (nothing), so I'll go ahead and merge.

**Pull request merged**
