### PR TITLE
Add snapping

### PR DESCRIPTION
**Pull request by adbl**
- Support snapping on a (invisible) 1-10 millimeter grid
  When enabled, placement and movement of shapes/handles is restricted to common horizontal/vertical intervals of the 
  snapping value.  
- Add settings dialog with the snapping settings

### CODE REVIEW

**Comment by raisjn** [comment]
can you share a screenshot or description of what this does? I'll add a button to control the setting this weekend if you don't beat me to it

**Comment by adbl** [comment]
> can you share a screenshot or description of what this does? I'll add a button to control the setting this weekend if you don't beat me to it

Certainly! It's just a draft yet. Basically it restricts placement of handles at x,y intervals of the snapping value. It also provides quite good visual feedback of it while moving the handles.

I'd like to add a settings button to the left of the Add menu to open a modal. There I would use the slider for tweaking snapping. It would be nice to also draw the "snap grid" in background for previewing. A snap offset setting would also be useful, to allow alignment with grid templates which may not start at (0,0).

I envision some other features which would be toggled on/off in the settings. Such as a "continuous" mode, to allow adding another shape by just tapping on the canvas. Haven't thought it through yet though.

**Comment by raisjn** [comment]
ah, sounds interesting! i pushed a commit with a settings dialog with snap range + toggle button in it for you to build on top of

**Comment by adbl** [comment]
Fabulous!

**Comment by raisjn** [comment]
i just tried this out, very cool! i'm thinking it might make sense to remove the ok/cancel button from the dialog (and always apply settings) by inheriting from an InfoDialog (instead of ConfirmationDialog)

do you have more plans or is it ready for review?

**Comment by adbl** [comment]
Glad you like it! I've gotten sidetracked by vacation a bit currently. 

There were something I wanted to clean up in code, can have a look tonight. 

I want to get saving/loading settings in, but I think this already provides some value so it can come later?

Always applying settings makes sense to me too, but I don't know if I'll have time to fix that in another week or so...

Other than this I think it's a reasonable PR.

**Comment by adbl** [comment]
Right, the millimeter value is slightly off. I'll try to find accurate hardware specs and check both device generations.

**Comment by adbl** [comment]
@raisjn hey, sorry for being quiet, family vacation and other stuff took over past weeks. just wanted to let you know this is very much still on my mind, I intend to push some last fixes to this branch coming days.  

Also, I spent a fair amount of time during vacation sketching on a sort of vision I haver for iago, which I'd like to spend time working towards, hopefully with your blessing of course (and support 😅)! Any chance we could connect and have a talk/call about them? you can reach me at andreas-github@amsenius.se

**Comment by adbl** [comment]
@raisjn finally got around to get the correct millimeter value. with your dialog change, I think this is ready...

**Comment by raisjn** [comment]
awesome :-D thanks for the upgrades and merging now!

**Review by raisjn — APPROVED** [review]

**Pull request merged**
